//INTERFACE
export interface IAction {
    type: string,
    payload?: any
}
//Weather Query
export const GET_WEATHER_QUERY_REQUEST = 'GET_WEATHER_QUERY_REQUEST'
export const GET_WEATHER_QUERY_SUCCESS = 'GET_WEATHER_QUERY_SUCCESS'
export const GET_WEATHER_QUERY_ERROR = 'GET_WEATHER_QUERY_ERROR'

//Weather Location
export const GET_WEATHER_LOCATION_REQUEST = 'GET_WEATHER_LOCATION_REQUEST'
export const GET_WEATHER_LOCATION_SUCCESS = 'GET_WEATHER_LOCATION_SUCCESS'
export const GET_WEATHER_LOCATION_ERROR = 'GET_WEATHER_LOCATION_ERROR'

export const GET_WEATHER_FORECAST_REQUEST = 'GET_WEATHER_FORECAST_REQUEST'
export const GET_WEATHER_FORECAST_SUCCESS = 'GET_WEATHER_FORECAST_SUCCESS'
export const GET_WEATHER_FORECAST_ERROR = 'GET_WEATHER_FORECAST_ERROR'